from pathlib import Path

REPO_PATH = Path(__file__).parent.parent
BIN_FILE_PATH = REPO_PATH / "c" / "bin" / "maps"
INPUT_FILE_PATH = REPO_PATH / "input"


LIMIT_ARG = "--limit"
ALTS_ARG = "-alts"
ALTF_ARG = "-altf"

RESULT_TITLE = "Результат"
HELP_TITLE = "Помощь"

FAILURE_TEXT = "Не удалось построить маршрут."

## MainWindow
MAIN_WINDOW_TITLE = "Основное окно"
MAIN_WINDOW_GEOMETRY = "600x350"
MAIN_WINDOW_BACKGROUND = "#008000"

# Default values
PRIORITY_DEFAULT_VALUE = "--quickest"
LIMIT_DEFAULT_VALUE = "0"
ALTS_DEFAULT_VALUE = "0"
ALTF_DEFAULT_VALUE = "1.0"

# Top frame config
TOP_FRAME_BACKGROUND = "#008000"

SRC_FRAME_BACKGROUND = "#008000"
SRC_FRAME_LABEL_TEXT = "Источник:"
SRC_FRAME_LABEL_BACKGROUND = "#008000"

DEST_FRAME_BACKGROUND = "#008000"
DEST_FRAME_LABEL_TEXT = "Назначение:"
DEST_FRAME_LABEL_BACKGROUND = "#008000"

PRIORITY_FRAME_BACKGROUND = "#008000"
PRIORITY_FRAME_LABEL_TEXT = "Назначение:"
PRIORITY_FRAME_LABEL_BACKGROUND = "#008000"
QUICKEST_BTN_VALUE = "--quickest"
LONGEST_BTN_VALUE = "--longest"
SHORTEST_BTN_VALUE = "--shortest"
PRIORITY_QUICKEST_TEXT = "Быстрый"
PRIORITY_LONGEST_TEXT = "Длинный"
PRIORITY_SHORTEST_TEXT = "Короткий"

# Middle frame config
MIDDLE_FRAME_BACKGROUND = "#008000"

LIMIT_FRAME_BACKGROUND = "#008000"
LIMIT_FRAME_LABEL_TEXT = "--limit"
LIMIT_FRAME_LABEL_BACKGROUND = "#008000"
LIMIT_SPINBOX_FROM = 0.0
LIMIT_SPINBOX_TO = 8.0

ALTS_FRAME_BACKGROUND = "#008000"
ALTS_FRAME_LABEL_TEXT = "-alts"
ALTS_FRAME_LABEL_BACKGROUND = "#008000"
ALTS_SPINBOX_FROM = 0.0
ALTS_SPINBOX_TO = 10.0

ALTF_FRAME_BACKGROUND = "#008000"
ALTF_FRAME_LABEL_TEXT = "-altf"
ALTF_FRAME_LABEL_BACKGROUND = "#008000"
ALTF_SPINBOX_FROM = 1.0
ALTF_SPINBOX_TO = 6.0
ALTF_SPINBOX_INCREMENT = 0.1

# Bottom frame config
BOTTOM_FRAME_BACKGROUND = "#008000"
SUBMIT_BTN_TEXT = "Подтвердить"
ALTS_BTN_TEXT = "Изменить маршрут"

HELP_BTN_TEXT = "Помощь"

## AltsWindow
ALTS_WINDOW_TITLE = "Выбор точки"
ALTS_WINDOW_GEOMETRY = "550x300"
ALTS_WINDOW_BACKGROUND = "#008000"

# Main frame config
MAIN_FRAME_BACKGROUND = "#008000"

ADD_FRAME_BACKGROUND = "#008000"
ADD_FRAME_LABEL_TEXT = "Список городов:"
ADD_FRAME_LABEL_BACKGROUND = "#008000"
SUBMIT_ADD_BTN_TEXT = "Добавить"

DEL_FRAME_BACKGROUND = "#008000"
DEL_FRAME_LABEL_TEXT = "Список городов:"
DEL_FRAME_LABEL_BACKGROUND = "#008000"
SUBMIT_DEL_BTN_TEXT = "Удалить"

## InfoWindow
INFO_WINDOW_GEOMETRY = "1500x600"
INFO_WINDOW_BACKGROUND = "#008000"
TEXT_WIDGET_BACKGROUND = "#008000"
TEXT_WIDGET_FOREGROUND = "#FFFFFF"
TEXT_WIDGET_FONT = ("Arial", 14)