name: CI

# Controls when the workflow will run
on:
  push:
  pull_request:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  style:
    runs-on: ubuntu-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4
      
      - name: Code Style check
        run: |
          echo "Checking code style..."
          git ls-files *.{c,h} | xargs clang-format -i --verbose && git diff --exit-code
  build:
    runs-on: ubuntu-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4
      
      - name: build test
        run: |
          make init
          echo "Compiling the code..."
          make
          echo "Compile complete."
  test: 
    runs-on: ubuntu-latest
    steps:
      # Running Unit-tests
      - uses: actions/checkout@v4

      - name: Unit-tests
        run: | 
          make init
          echo "Start testing functions..."
          make test
          echo "Tests complete."
